spring:
  application.name: porio
  graphql.graphiql.enabled: true
  data.mongodb:
    uri: mongodb+srv://porio:${MONGO_PASSWORD}@cluster0.wmgrcpo.mongodb.net/?retryWrites=true&w=majority&appName=porio
    database: porio

