name: Deploy GitHub Pages

on:
  push:
    branches:
      - ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UI branch
        uses: actions/checkout@v4
        with:
          ref: ui

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
